on: [push]

jobs:
  Notion_Hook_job:
    runs-on: ubuntu-latest
    name: Sync your commits to Notion
    steps:
      - name: Connect to Notion step
        id: notion
        uses: alessandrobelli/NotionHook@beta
        with:
          notion_secret: ${{ secrets.NOTION_SECRET }}
          notion_database: ${{ secrets.NOTION_DATABASE }}
          files_format: 'string-delimited'
          token: ${{ secrets.TOKEN }}

